src/dashbord/urls.py
from django.urls import path
from dashbord.views import index

app_name = "dashboard"
urlpatterns = [
    path("", index, name="dashboard")
]

src/eleve/urls.py
from django.urls import path
from eleve.views import index, add, update

#nom de notre application dans l'url (localhost:8000/eleve/) par la variable app_name
app_name = "eleve"

urlpatterns = [
    path("", index, name="eleve"),
    
    path("ajout_eleve", add, name="add"),
    path("modif_eleve", update, name="update")
]

src/professeur/urls.py
from django.urls import path
from professeur.views import index, add, update

app_name = "professeur"
urlpatterns = [ 
    path('',index, name="professeur"),
    path('ajouter_professeur',add, name="add"),
    path('modifier_professeur',update, name="update")
]

src/rapport/urls.py
from django.urls import path
from rapport.views import index

app_name ="rapport"

urlpatterns = [
    path('', index, name="rapport"),
    
]

src/utilisateur/urls.py
from django.urls import path
from utilisateur.views import index, add, update, login

app_name = "utilisateur"
urlpatterns = [
    path('',index, name="utilisateur"),
    path('ajouter_utilisateur',add, name="add"),
    path('modifier_utilisateur',update, name="update"),
    path('login',login)
]

src/website/urls.py
from django.contrib import admin
from django.urls import include,path
from eleve.views import index
from dashbord.views import index
from professeur.views import index
from utilisateur.views import index, login
from rapport.views import index

urlpatterns = [
    path("",login),
    path("admin/", admin.site.urls),
    path('eleve/', include('eleve.urls')),
    path('dashbord/', include('dashbord.urls')),
    path('professeur/',include('professeur.urls')),
    path('utilisateur/',include('utilisateur.urls')),
    path('rapport/',include('rapport.urls'))
    
    
]

src/dashbord/models.py
from django.db import models

# Create your models here.

src/eleve/models.py
from django.db import models

# Create your models here.
class Eleve(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    birth_date = models.DateField()
    phone = models.CharField(max_length=10)
    classrom = models.CharField(max_length=10)
    registration_number = models.CharField(max_length=30)
    
    

src/professeur/models.py
from django.db import models

# Create your models here.

class Professeur(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    birth_date = models.DateField()
    phone = models.CharField(max_length=10)
    is_vacant = models.BooleanField()
    matter = models.CharField(max_length=30)
    next_class = models.CharField(max_length=30)
    subject_next_meeting = models.CharField(max_length=100)
    

src/rapport/models.py
from django.db import models

# Create your models here.

src/utilisateur/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    pseudo = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=15)
    creat_at = models.DateField(auto_now_add=True)
    

src/eleve/forms.py
from django import forms


class StudentForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    birth_date = forms.DateField()
    phone = forms.CharField(max_length=10)
    classrom = forms.CharField(max_length=10)
    registration_number = forms.CharField(max_length=30)
    
    

src/professeur/forms.py
from django import forms

class TeacherForm(forms.Form):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    city = forms.CharField(max_length=100)
    birth_date = forms.DateField()
    phone = forms.CharField(max_length=10)
    is_vacant = forms.BooleanField()
    matter = forms.CharField(max_length=30)
    next_class = forms.CharField(max_length=30)
    subject_next_meeting = forms.CharField(max_length=100)

src/utilisateur/forms.py
from django import forms
from .models import User

class UserForm(forms.Form):
    pseudo = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30)
    creat_at = forms.DateTimeField()


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['pseudo', 'password',]
        
       # exclude = ['creat_at']
        

src/dashbord/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "dashbord/index.html", )

src/eleve/views.py
from django.shortcuts import render
from .forms import StudentForm

# Create your views here.


def index(request):
    return render(request, "eleve/index.html")

def add(request):
    form = StudentForm()
    context = {'Form': form}
    return render(request, "eleve/ajout_eleve.html", context )

def update(request):
    return render(request, "eleve/modif_eleve.html")

src/professeur/views.py
from django.shortcuts import render
from .forms import TeacherForm

# Create your views here.

def index(request):
    return render(request, "professeur/index.html")

def add(request):
    form = TeacherForm()
    content = {'Form': form}
    return render(request,"professeur/ajout_prof.html", content )

def update(request):
    return render(request, "professeur/modif_prof.html")

src/rapport/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'rapport/index.html' )

src/utilisateur/views.py
from django.shortcuts import render
from .forms import UserForm

# Create your views here.

def index(request):
    return render(request,"utilisateur/index.html")

def add(request):
    
    if request.method == 'POST':
        #print(request.POST)
        
        user_form = UserForm(request.POST)
        if user_form.is_valid():
            print(user_form.cleaned_data)
            user_form.save()
        
        
    user_form = UserForm()
    context = {'user_form':user_form}
    return render(request, "utilisateur/ajout_user.html", context)

def update(request):
    return render(request, "utilisateur/modif_user.html")
def login(request):
    return render(request,"utilisateur/login.html")

src/dashbord/templates/dashbord/index copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en"> 
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'dashbord/css/style.css' %}">
        <title>DASHBOARD</title>
    </head>     
    <body>
        <div class="container">
            <aside>
                <div class="top">
                    <div class="logo">
                        <h2>Mon<span class="danger">Etab</span></h2>
                    </div>
                    <div class="close" id="close-btn">
                        <span class="material-icons sharp">close</span>
                    </div>
                </div>
                <div class="sidebar">
                    <a href="{% url 'dashboard:dashboard'%}">
                        <span class="material-icons sharp">dashboard</span>
                        <h3>Dashboard</h3>
                    </a>
                    <a href="{% url 'eleve:eleve'%}" class="active">
                        <span class="material-icons sharp">groups</span>
                        <h3>élèves</h3>
                    </a>
                    <a href="{% url 'professeur:professeur'%}">
                        <span class="material-icons sharp">supervisor_account</span>
                        <h3>Professeurs</h3>
                    </a>
                    <a href="{% url 'utilisateur:utilisateur'%}">
                        <span class="material-icons sharp">person</span>
                        <h3>Utilisateurs</h3>
                    </a>
                    <a href="{% url 'rapport:rapport'%}">
                        <span class="material-icons sharp">analytics</span>
                        <h3>Rapports</h3>
                    </a>

                    <a href="/login.html">
                        <span class="material-icons sharp">logout</span>
                       
                        <h3>Déconnexion</h3>
                    </a>
                </div>
            </aside>
            <main>
                <h1>Tableau de bord</h1>
                <div class="date">
                    <input type="date">
                </div>
    
                <div class="insights">
                    <div class="sales">
                        <!--<span class="material-icons-sharp">groups</span>-->
                        <div class="middle">
                            <div class="left">
                                <h3>Nombre d'etudiants</h3>
                                <h1>128 100</h1>
                            </div>
                           <!--- <div class="progress">
                                <svg>
                                    <circle cx="38" cy="38" r="36"></circle>
                                </svg>
                            </div>  -->
                        </div>
                       <!--- <small class="text-muted">Last 24 hours</small> -->
                    </div>

                    <!-- END OF ELEVE  -->
                    <div class="expenses">
                        <!--<span class="material-icons-sharp">supervisor_account</span> -->
                        <div class="middle">
                            <div class="left">
                                <h3>Nombre de professeurs</h3>
                                <h1>128 100</h1>
                            </div>
                            <div class="progress">
                              <!--  <svg>
                                    <circle cx="38" cy="38" r="36"></circle>
                                </svg>-->
                            </div> 
                        </div>
                        <!--<small class="text-muted">Last 24 hours</small>-->
                    </div>

                    <!-- END OF PROF     -->
                    <div class="income">
                        <!---<span class="material-icons-sharp">groups</span>-->
                        <div class="middle">
                            <div class="left">
                                <h3>Nombre d'utilisateurs</h3>
                                <h1>128 100</h1>
                            </div>
                           <div class="progress">
                                <!--<svg>
                                    <circle cx="38" cy="38" r="36"></circle>
                                </svg>--> 
                            </div>
                        </div>
                        <!--<small class="text-muted">Last 24 hours</small> -->
                    </div>

                    <!-- END OF utilisateurs -->
                    <div class="middle">
                        <canvas id="genderChart"></canvas>
                    </div>

                    <!-- END OF SALES -->
                </div>

              <!--<div class="recent-orders">
                    <h2>Elèves</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>Nom</th>
                                <th>Prènom</th>
                                <th>Genre</th>
                                <th>Classe</th>
                                <th>Matricule</th>
                                <th>Age</th>
                                <th>Télephone</th>
                                <th>Ville</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Koffi</td>
                                <td>George</td>
                                <td>M</td>
                                <td>Tle</td>
                                <td>GDJ7GDGD</td>
                                <td>25</td>
                                <td>0712345678</td>
                                <td>Bonoua</td>
                                <td >
                                    <button class="primary">Modifier</button>
                                    <button class="danger">Supprimer</button>
                                </td>

                            </tr>
                            <tr>
                                <td>KONÉ</td>
                                <td>Sali</td>
                                <td>F</td>
                                <td>2nd</td>
                                <td>GDJ7GDGD</td>
                                <td>22</td>
                                <td>0712345678</td>
                                <td>Abidjan</td>
                                <td >
                                    <button class="primary">Modifier</button>
                                    <button class="danger">Supprimer</button>
                                </td>

                            </tr>
                        </tbody>
                    </table>
                    <a href="#">Voir plus</a>
                </div>-->  
            </main>
                <!-- END OF MAIN -->
                 <div class="right">
                    <div class="top">
                        <button id="menu-btn">
                            <span class="material-symbols-outlined">
                                menu
                                </span>
                        </button>
                        <div class="theme-toggler">
                            <span class="material-symbols-outlined active">light_mode</span>
                            <span class="material-symbols-outlined">dark_mode</span>
                        </div>

                        <div class="profile">
                            <div class="info">
                                <p>Hey, <b>Koffi</b></p>
                                <small class="text-muted">Admin</small>
                            </div>
                            <div class="profile-photo">
                                <img src="asset/img/profile-1.jpg">
                            </div>
                        </div>
                    </div>
                 </div>
                 <!-- END OF RIGHT -->
                  <div class="recent-updates">

                  </div>
        </div>

        <script src="{% static 'dashbord/js/menu.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        
        <script src="{% static 'dashbord/js/graph.js' %}"></script>
    </body> 
    
</html>

src/dashbord/templates/dashbord/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'dashbord/css/style.css' %} ">
        <title>{%block title%} {%endblock%}</title>
    </head>     
    <body>
        <div class="container">
            <aside>
                <div class="top">
                    <div class="logo">
                        <h2>Mon<span class="danger">Etab</span></h2>
                    </div>
                    <div class="close" id="close-btn">
                        <span class="material-icons sharp">close</span>
                    </div>
                </div>
                <div class="sidebar">
                    <a href="{% url 'dashboard:dashboard'%}">
                        <span class="material-icons sharp">dashboard</span>
                        <h3>Dashboard</h3>
                    </a>
                    <a href="{% url 'eleve:eleve'%}" class="active">
                        <span class="material-icons sharp">groups</span>
                        <h3>élèves</h3>
                    </a>
                    <a href="{% url 'professeur:professeur'%}">
                        <span class="material-icons sharp">supervisor_account</span>
                        <h3>Professeurs</h3>
                    </a>
                    <a href="{% url 'utilisateur:utilisateur'%}">
                        <span class="material-icons sharp">person</span>
                        <h3>Utilisateurs</h3>
                    </a>
                    <a href="{% url 'rapport:rapport'%}">
                        <span class="material-icons sharp">analytics</span>
                        <h3>Rapports</h3>
                    </a>

                    <a href="/login.html">
                        <span class="material-icons sharp">logout</span>
                       
                        <h3>Déconnexion</h3>
                    </a>
                </div>
            </aside>
            {% block content %}

            {% endblock  %}
            <div class="right">
                <div class="top">
                    <button id="menu-btn">
                        <span class="material-symbols-outlined">
                            menu
                            </span>
                    </button>
                    <div class="theme-toggler">
                        <span class="material-symbols-outlined active">light_mode</span>
                        <span class="material-symbols-outlined">dark_mode</span>
                    </div>

                    <div class="profile">
                        <div class="info">
                            <p>Hey, <b>Koffi</b></p>
                            <small class="text-muted">Admin</small>
                        </div>
                        <div class="profile-photo">
                            <img src="asset/img/profile-1.jpg">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

        <script src="{% static 'dashbord/js/menu.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        
        <script src="{% static 'dashbord/js/graph.js' %}"></script>
    </body> 
    
    </html>

src/eleve/templates/eleve/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'eleve/css/style.css' %} ">
        <title>{%block title%} {%endblock%}</title>
    </head>     
    <body>
        <div class="container">
            <aside>
                <div class="top">
                    <div class="logo">
                        <h2>Mon<span class="danger">Etab</span></h2>
                    </div>
                    <div class="close" id="close-btn">
                        <span class="material-icons sharp">close</span>
                    </div>
                </div>
                <div class="sidebar">
                    <a href="{% url 'dashboard:dashboard'%}">
                        <span class="material-icons sharp">dashboard</span>
                        <h3>Dashboard</h3>
                    </a>
                    <a href="{% url 'eleve:eleve'%}" class="active">
                        <span class="material-icons sharp">groups</span>
                        <h3>élèves</h3>
                    </a>
                    <a href="{% url 'professeur:professeur'%}">
                        <span class="material-icons sharp">supervisor_account</span>
                        <h3>Professeurs</h3>
                    </a>
                    <a href="{% url 'utilisateur:utilisateur'%}">
                        <span class="material-icons sharp">person</span>
                        <h3>Utilisateurs</h3>
                    </a>
                    <a href="{% url 'rapport:rapport'%}">
                        <span class="material-icons sharp">analytics</span>
                        <h3>Rapports</h3>
                    </a>

                    <a href="/login.html">
                        <span class="material-icons sharp">logout</span>
                       
                        <h3>Déconnexion</h3>
                    </a>
                </div>
            </aside>
            {% block content %}

            {% endblock  %}
            <div class="right">
                <div class="top">
                    <button id="menu-btn">
                        <span class="material-symbols-outlined">
                            menu
                            </span>
                    </button>
                    <div class="theme-toggler">
                        <span class="material-symbols-outlined active">light_mode</span>
                        <span class="material-symbols-outlined">dark_mode</span>
                    </div>

                    <div class="profile">
                        <div class="info">
                            <p>Hey, <b>Koffi</b></p>
                            <small class="text-muted">Admin</small>
                        </div>
                        <div class="profile-photo">
                            <img src="asset/img/profile-1.jpg">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

        <script src="{% static 'eleve/js/menu.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        
        
    </body> 
    
    </html>

src/professeur/templates/professeur/layout/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'professeur/css/style.css' %} ">
        <title>{%block title%} {%endblock%}</title>
    </head>     
    <body>
        <div class="container">
            <aside>
                <div class="top">
                    <div class="logo">
                        <h2>Mon<span class="danger">Etab</span></h2>
                    </div>
                    <div class="close" id="close-btn">
                        <span class="material-icons sharp">close</span>
                    </div>
                </div>
                <div class="sidebar">
                    <a href="{% url 'dashboard:dashboard'%}">
                        <span class="material-icons sharp">dashboard</span>
                        <h3>Dashboard</h3>
                    </a>
                    <a href="{% url 'eleve:eleve'%}" class="active">
                        <span class="material-icons sharp">groups</span>
                        <h3>élèves</h3>
                    </a>
                    <a href="{% url 'professeur:professeur'%}">
                        <span class="material-icons sharp">supervisor_account</span>
                        <h3>Professeurs</h3>
                    </a>
                    <a href="{% url 'utilisateur:utilisateur'%}">
                        <span class="material-icons sharp">person</span>
                        <h3>Utilisateurs</h3>
                    </a>
                    <a href="{% url 'rapport:rapport'%}">
                        <span class="material-icons sharp">analytics</span>
                        <h3>Rapports</h3>
                    </a>

                    <a href="/login.html">
                        <span class="material-icons sharp">logout</span>
                       
                        <h3>Déconnexion</h3>
                    </a>
                </div>
            </aside>
            {% block content %}

            {% endblock  %}
            <div class="right">
                <div class="top">
                    <button id="menu-btn">
                        <span class="material-symbols-outlined">
                            menu
                            </span>
                    </button>
                    <div class="theme-toggler">
                        <span class="material-symbols-outlined active">light_mode</span>
                        <span class="material-symbols-outlined">dark_mode</span>
                    </div>

                    <div class="profile">
                        <div class="info">
                            <p>Hey, <b>Koffi</b></p>
                            <small class="text-muted">Admin</small>
                        </div>
                        <div class="profile-photo">
                            <img src="asset/img/profile-1.jpg">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        

        <script src="{% static 'professeur/js/menu.js' %}"></script>
        
    </body> 
    
    </html>

src/rapport/templates/rapport/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <link rel="stylesheet" href="{% static 'rapport/css/style.css' %} ">
        <title>DASHBOARD</title>
    </head>     
    <body>
        <div class="container">
            <aside>
                <div class="top">
                    <div class="logo">
                        <h2>Mon<span class="danger">Etab</span></h2>
                    </div>
                    <div class="close" id="close-btn">
                        <span class="material-icons sharp">close</span>
                    </div>
                </div>
                <div class="sidebar">
                    <a href="{% url 'dashboard:dashboard'%}">
                        <span class="material-icons sharp">dashboard</span>
                        <h3>Dashboard</h3>
                    </a>
                    <a href="{% url 'eleve:eleve'%}" class="active">
                        <span class="material-icons sharp">groups</span>
                        <h3>élèves</h3>
                    </a>
                    <a href="{% url 'professeur:professeur'%}">
                        <span class="material-icons sharp">supervisor_account</span>
                        <h3>Professeurs</h3>
                    </a>
                    <a href="{% url 'utilisateur:utilisateur'%}">
                        <span class="material-icons sharp">person</span>
                        <h3>Utilisateurs</h3>
                    </a>
                    <a href="{% url 'rapport:rapport'%}">
                        <span class="material-icons sharp">analytics</span>
                        <h3>Rapports</h3>
                    </a>

                    <a href="/login.html">
                        <span class="material-icons sharp">logout</span>
                       
                        <h3>Déconnexion</h3>
                    </a>
                </div>
            </aside>
            <main class="main-content">
                <div class="header">
                    <a href="{%url 'rapport:rapport'%}" class="back-button">← Retour</a>
                </div>
                <h1>Rapport</h1>
                <form class="form">
    
                    <div class="form-group">
                        <label for="rapport">Sélectionner une option</label>
                        <select id="rapport" name="rapport" required>
                            <option value="Liste des élèves">Liste des élèves</option>
                            <option value="Liste des professeurs">Liste des professeurs</option>
                            <option value="Liste des utilisateurs">Liste des utilisateurs</option>
                           
                        </select>
                    </div>

    
                    <div class="form-actions">
                        <button type="reset" class="btn cancel">Généner format PDF</button>
                        <button type="submit" class="btn save">Généner format Excel</button>
                    </div>
                </form>
            </main>
                <!-- END OF MAIN -->
                 <div class="right">
                    <div class="top">
                        <button id="menu-btn">
                            <span class="material-symbols-outlined">
                                menu
                                </span>
                        </button>
                        <div class="theme-toggler">
                            <span class="material-symbols-outlined active">light_mode</span>
                            <span class="material-symbols-outlined">dark_mode</span>
                        </div>

                        <div class="profile">
                            <div class="info">
                                <p>Hey, <b>Koffi</b></p>
                                <small class="text-muted">Admin</small>
                            </div>
                            <div class="profile-photo">
                                <img src="asset/img/profile-1.jpg">
                            </div>
                        </div>
                    </div>
                 </div>
                 <!-- END OF RIGHT -->
                  <div class="recent-updates">

                  </div>
        </div>

        <script src="/asset/js/menu.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        
        <script src="/asset/js/graph.js"></script>
    </body> 
    
</html>